name: LinucxMD

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 7,9,11 * * 1,3" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED By YusupKakuu
          
      - name: Commit changes
        run: |
          git config --local user.email "linucxmd@gmail.com"
          git config --local user.name "NeofetchNpc"
          git add -A
          
          arr[0]="chore(ai): 💜"
          arr[1]="chore(bot): 🖤"
          arr[2]="chore(ai): 💙"
          arr[3]="chore(bot): 🩷"
          arr[4]="chore(ai): 🧡"
          arr[5]="chore(bot): 💛"
          arr[6]="chore(ai): 🐐"
          arr[7]="chore(bot): 🤎"
          arr[8]="chore(ai): 🩶"
          arr[9]="chore(bot): 💣"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GHB_TOKEN }}
